import AdminReport from "../../models/AdminReport.js";
import Record from "../../models/Record.js";
import Counselor from "../../models/Counselor.js";
import ActivityLog from "../../models/ActivityLog.js";
import fs from "fs";
import path from "path";
import { generateCounselingRecordPDF } from "../../utils/pdfUtils.js";
import {
  generateCounselingSummaryPdf,
  buildSummaryMonthLabel,
  buildSummaryMonthLabelFromRecords,
  inferSummarySchoolYear,
} from "../../utils/counselingSummaryPdf.js";
import { google } from "googleapis";
import { getDriveClientFromRequest, getOrCreateReportsFolder } from "../../utils/driveUtils.js";
import mongoose from "mongoose";
import { notArchivedFilter, isArchivedFilter } from "../../config/recordArchive.js";

// Helper function to generate tracking number
const generateTrackingNumber = () => {
  const timestamp = Date.now();
  const random = Math.floor(Math.random() * 10000).toString().padStart(4, "0");
  return `DOC-${timestamp}-${random}`;
};

// Helper to get user info from request
const getUserInfo = (req) => {
  return {
    userId: req.admin?._id || req.user?._id,
    userName: req.admin?.name || req.admin?.email || req.user?.name || req.user?.email || "Unknown Admin",
    userEmail: req.admin?.email || req.user?.email || "unknown@example.com",
    userModel: req.admin?._id ? "Admin" : "Counselor",
  };
};

// Helper to log activity
/** Shared Mongo filter for admin report types that query counseling records. */
async function buildAdminRecordsFilter({
  clientName,
  counselorName,
  status,
  recordType,
  sessionType,
  startDate,
  endDate,
  counselorId,
  archived,
}) {
  const filter = {};
  if (clientName && String(clientName).trim() !== "") {
    filter.clientName = { $regex: String(clientName).trim(), $options: "i" };
  }
  if (recordType && String(recordType).trim() !== "") {
    filter.status = recordType;
  } else if (status && String(status).trim() !== "") {
    filter.status = status;
  }
  if (sessionType && String(sessionType).trim() !== "") {
    filter.sessionType = sessionType;
  }
  if (startDate && endDate) {
    filter.date = { $gte: new Date(startDate), $lte: new Date(endDate) };
  } else if (startDate) {
    filter.date = { $gte: new Date(startDate) };
  } else if (endDate) {
    filter.date = { $lte: new Date(endDate) };
  }

  const cid = counselorId != null ? String(counselorId).trim() : "";
  if (cid && mongoose.Types.ObjectId.isValid(cid)) {
    const c = await Counselor.findById(cid).select("name email").lean();
    if (c) {
      const parts = [];
      if (c.name) parts.push({ counselor: c.name });
      if (c.email) parts.push({ counselor: c.email });
      if (parts.length) filter.$or = parts;
    }
  } else if (counselorName && String(counselorName).trim() !== "") {
    filter.counselor = { $regex: String(counselorName).trim(), $options: "i" };
  }

  const archFrag =
    archived === true || archived === "true" ? isArchivedFilter() : notArchivedFilter();
  if (Object.keys(filter).length === 0) {
    return archFrag;
  }
  return { $and: [filter, archFrag] };
}

const logActivity = async (req, activityType, description, metadata = {}) => {
  try {
    const userInfo = getUserInfo(req);
    const activityLog = new ActivityLog({
      userId: userInfo.userId,
      userModel: userInfo.userModel === "Admin" ? "Admin" : "Counselor",
      userEmail: userInfo.userEmail,
      userName: userInfo.userName,
      activityType,
      description,
      ipAddress: req.ip || req.connection?.remoteAddress,
      userAgent: req.headers["user-agent"],
      metadata,
    });
    await activityLog.save();
  } catch (error) {
    console.error("Failed to log activity:", error);
    // Don't throw - activity logging should not break the main flow
  }
};

const buildAdminPdfRecord = ({ reportName, reportType, records, statistics, userInfo, reportDate, filter }) => {
  const summaryLines = [
    `Report Name: ${reportName}`,
    `Report Type: ${reportType}`,
    `Generated By: ${userInfo.userName}`,
    `Generated On: ${reportDate}`,
    `Total Matching Records: ${records.length}`,
  ];

  Object.entries(filter || {}).forEach(([key, value]) => {
    if (value !== undefined && value !== null && value !== "") {
      summaryLines.push(`${key}: ${typeof value === "object" ? JSON.stringify(value) : value}`);
    }
  });

  const statisticLines = Object.entries(statistics || {}).map(([key, value]) => {
    const label = key.replace(/([A-Z])/g, " $1").replace(/^./, (str) => str.toUpperCase());
    return `${label}: ${value}`;
  });

  const firstRecord = records[0] || {};

  return {
    clientName: reportName,
    date: new Date(),
    sessionNumber: records.length || 0,
    sessionType: reportType,
    status: "Generated",
    counselor: userInfo.userName,
    notes: summaryLines.concat(
      records.length
        ? ["", "Top Record Preview:", `Client: ${firstRecord.clientName || "N/A"}`, `Date: ${firstRecord.date ? new Date(firstRecord.date).toLocaleDateString() : "N/A"}`, `Status: ${firstRecord.status || "N/A"}`, `Counselor: ${firstRecord.counselor || "N/A"}`]
        : ["", "No records matched the selected filters."]
    ).join("\n"),
    outcomes: statisticLines.length ? statisticLines.join("\n") : "No summary statistics available.",
  };
};

/**
 * Get Reports Dashboard Overview
 */
export const getReportsOverview = async (req, res) => {
  try {
    // Total Counseling Records
    const totalRecords = await Record.countDocuments();

    // Total Completed Sessions
    const completedSessions = await Record.countDocuments({ status: "Completed" });

    // Total Ongoing Sessions
    const ongoingSessions = await Record.countDocuments({ status: "Ongoing" });

    // Total Counselors
    const totalCounselors = await Counselor.countDocuments({ role: "counselor" });

    // Total Generated PDFs (records with driveLink)
    const totalPDFs = await Record.countDocuments({
      driveLink: { $exists: true, $ne: null, $ne: "" },
    });

    // Files Uploaded to Google Drive (same as PDFs for now)
    const filesUploaded = await Record.countDocuments({
      driveLink: { $exists: true, $ne: null, $ne: "" },
    });

    res.status(200).json({
      success: true,
      overview: {
        totalRecords,
        completedSessions,
        ongoingSessions,
        totalCounselors,
        totalPDFs,
        filesUploaded,
      },
    });
  } catch (error) {
    console.error("❌ Error fetching reports overview:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch reports overview",
      error: error.message,
    });
  }
};

/**
 * Get filtered records for report generation
 */
export const getFilteredRecords = async (req, res) => {
  try {
    const {
      reportType,
      clientName,
      counselorName,
      status,
      recordType,
      sessionType,
      startDate,
      endDate,
      counselorId,
      page = 1,
      limit = 3,
    } = req.query;

    const filter = await buildAdminRecordsFilter({
      clientName,
      counselorName,
      status,
      recordType,
      sessionType,
      startDate,
      endDate,
      counselorId,
    });

    // Calculate pagination
    const pageNum = parseInt(page);
    const limitNum = parseInt(limit);
    const skip = (pageNum - 1) * limitNum;

    // Get total count
    const total = await Record.countDocuments(filter);

    // Get records
    const records = await Record.find(filter)
      .sort({ date: -1 })
      .skip(skip)
      .limit(limitNum)
      .lean();

    res.status(200).json({
      success: true,
      records,
      pagination: {
        page: pageNum,
        limit: limitNum,
        total,
        totalPages: Math.ceil(total / limitNum),
      },
      filter,
    });
  } catch (error) {
    console.error("❌ Error fetching filtered records:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch filtered records",
      error: error.message,
    });
  }
};

/**
 * Generate PDF Report
 */
export const generateReport = async (req, res) => {
  try {
    const {
      reportType,
      reportName,
      clientName,
      counselorName,
      status,
      recordType,
      sessionType,
      startDate,
      endDate,
      counselorId,
    } = req.body;

    if (!reportType || !reportName) {
      return res.status(400).json({
        success: false,
        message: "Report type and report name are required",
      });
    }

    const userInfo = getUserInfo(req);
    const trackingNumber = generateTrackingNumber();
    const reportDate = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const filter = await buildAdminRecordsFilter({
      clientName,
      counselorName,
      status,
      recordType,
      sessionType,
      startDate,
      endDate,
      counselorId,
    });

    // Fetch data based on report type
    let records = [];
    let statistics = {};

    switch (reportType) {
      case "Counseling Records Report":
        records = await Record.find(filter).sort({ date: -1 }).lean();
        statistics = {
          totalRecords: records.length,
          completedSessions: records.filter((r) => r.status === "Completed").length,
          ongoingSessions: records.filter((r) => r.status === "Ongoing").length,
          referredSessions: records.filter((r) => r.status === "Referred").length,
        };
        break;
      case "Counseling Summary Report": {
        const matchCount = await Record.countDocuments(filter);
        if (matchCount > 500) {
          return res.status(400).json({
            success: false,
            message: `Too many records (${matchCount}) match your filters. Counseling summary reports are limited to 500 records. Narrow the date range or add filters.`,
          });
        }
        records = await Record.find(filter).sort({ date: 1 }).limit(500).lean();
        if (records.length === 0) {
          return res.status(400).json({
            success: false,
            message: "No records match your filters. Cannot generate an empty counseling summary.",
          });
        }
        statistics = {
          totalRecords: records.length,
          completedSessions: records.filter((r) => r.status === "Completed").length,
          ongoingSessions: records.filter((r) => r.status === "Ongoing").length,
          referredSessions: records.filter((r) => r.status === "Referred").length,
        };
        break;
      }
      default:
        return res.status(400).json({
          success: false,
          message: "Invalid report type",
        });
    }


    const sanitizedReportName = reportName.replace(/[^a-zA-Z0-9]/g, "_");
    const sanitizedAdminName = userInfo.userName.replace(/[^a-zA-Z0-9]/g, "_");

    let pdfPath;
    let generatedPdfFileName;

    if (reportType === "Counseling Summary Report") {
      const monthLabel =
        startDate || endDate
          ? buildSummaryMonthLabel(startDate, endDate)
          : buildSummaryMonthLabelFromRecords(records);
      const schoolYear = inferSummarySchoolYear(records);
      const tempSummaryPath = await generateCounselingSummaryPdf(records, {
        monthLabel,
        schoolYear,
        trackingNumber,
        reportDate,
      });
      const desiredName = `counseling_summary_${trackingNumber}.pdf`;
      const targetPath = path.join(path.dirname(tempSummaryPath), desiredName.replace(/[^\w.\-]/g, "_"));
      try {
        if (tempSummaryPath !== targetPath && fs.existsSync(tempSummaryPath)) {
          if (fs.existsSync(targetPath)) fs.unlinkSync(targetPath);
          fs.renameSync(tempSummaryPath, targetPath);
          pdfPath = targetPath;
        } else {
          pdfPath = tempSummaryPath;
        }
      } catch (renameErr) {
        console.error("Summary PDF rename failed, using temp name:", renameErr.message);
        pdfPath = tempSummaryPath;
      }
      generatedPdfFileName = path.basename(pdfPath);
    } else {
      const pdfRecord = buildAdminPdfRecord({
        reportName,
        reportType,
        records,
        statistics,
        userInfo,
        reportDate,
        filter,
      });
      pdfPath = await generateCounselingRecordPDF(pdfRecord, `${sanitizedAdminName}_${sanitizedReportName}`);
      generatedPdfFileName = path.basename(pdfPath);
    }

    // Get file size
    const stats = fs.statSync(pdfPath);
    const fileSize = stats.size;

    // Upload to Google Drive (uses logged-in admin's account when signed in with Google)
    let driveFileId = null;
    let driveLink = null;
    let driveUploadStatus = "failed";
    let driveUploadError = null;

    try {
      const drive = await getDriveClientFromRequest(req);
      if (drive) {
        const fileName = generatedPdfFileName;
        const media = {
          mimeType: "application/pdf",
          body: fs.createReadStream(pdfPath),
        };
        const folderId = process.env.GOOGLE_DRIVE_FOLDER_ID;

        let file;
        try {
          file = await drive.files.create({
            resource: {
              name: fileName,
              parents: folderId ? [folderId] : [],
            },
            media,
            fields: "id, webViewLink",
          });
        } catch (folderErr) {
          if (folderId && (folderErr.code === 404 || folderErr.code === 403 || String(folderErr.message || "").includes("not found"))) {
            const userFolderId = await getOrCreateReportsFolder(drive);
            if (userFolderId) {
              file = await drive.files.create({
                resource: { name: fileName, parents: [userFolderId] },
                media,
                fields: "id, webViewLink",
              });
            } else {
              file = await drive.files.create({
                resource: { name: fileName },
                media,
                fields: "id, webViewLink",
              });
            }
          } else {
            throw folderErr;
          }
        }

        driveFileId = file.data.id;
        driveLink = file.data.webViewLink;
        driveUploadStatus = "success";
      } else {
        driveUploadError = "Sign in with Google to upload reports to Drive";
      }
    } catch (driveError) {
      console.error("❌ Google Drive upload failed:", driveError);
      driveUploadStatus = "failed";
      driveUploadError = driveError.message || "Unknown error";
    }

    // Save report to database
    const adminReport = new AdminReport({
      reportName,
      reportType,
      trackingNumber,
      generatedBy: {
        userId: userInfo.userId,
        userName: userInfo.userName,
        userEmail: userInfo.userEmail,
        userModel: userInfo.userModel,
      },
      filterCriteria: {
        ...(clientName && typeof clientName === "string" && clientName.trim() !== "" && { clientName }),
        ...(counselorName && typeof counselorName === "string" && counselorName.trim() !== "" && { counselorName }),
        ...(status && typeof status === "string" && status.trim() !== "" && { status }),
        ...(recordType && typeof recordType === "string" && recordType.trim() !== "" && { recordType }),
        ...(sessionType && typeof sessionType === "string" && sessionType.trim() !== "" && { sessionType }),
        ...(startDate && { startDate: new Date(startDate) }),
        ...(endDate && { endDate: new Date(endDate) }),
        ...(counselorId && typeof counselorId === "string" && counselorId.trim() !== "" && mongoose.Types.ObjectId.isValid(counselorId) && { counselorId }),
      },
      statistics,
      driveFileId,
      driveLink,
      driveUploadStatus,
      driveUploadError,
      fileName: generatedPdfFileName,
      fileSize,
      reportData: {
        recordCount: records.length,
      },
    });

    await adminReport.save();

    // Log activity
    await logActivity(req, "report_generated", `Generated ${reportType}: ${reportName}`, {
      reportId: adminReport._id,
      trackingNumber,
      reportType,
    });

    // Clean up temp file after a delay (allow time for download)
    setTimeout(() => {
      try {
        if (fs.existsSync(pdfPath)) {
          fs.unlinkSync(pdfPath);
        }
      } catch (err) {
        console.error("Failed to delete temp file:", err);
      }
    }, 60000); // Delete after 1 minute

    // Return report metadata and prepare for file download
    res.status(200).json({
      success: true,
      message: "Report generated successfully",
      report: {
        id: adminReport._id,
        reportName,
        trackingNumber,
        driveLink,
        driveUploadStatus,
        driveUploadError,
        createdAt: adminReport.createdAt,
        fileName: generatedPdfFileName,
        downloadPath: `/api/admin/reports/${adminReport._id}/download-pdf`,
      },
    });
  } catch (error) {
    console.error("❌ Error generating report:", error);
    res.status(500).json({
      success: false,
      message: "Failed to generate report. Please try again.",
      error: error.message,
    });
  }
};

/**
 * Get all generated reports
 */
export const getAllReports = async (req, res) => {
  try {
    const { page = 1, limit = 3, reportType, sortBy = "createdAt", order = "desc" } = req.query;

    const filter = {};
    if (reportType) filter.reportType = reportType;

    const pageNum = parseInt(page);
    const limitNum = parseInt(limit);
    const skip = (pageNum - 1) * limitNum;

    const sortOption = {};
    sortOption[sortBy] = order === "desc" ? -1 : 1;

    const total = await AdminReport.countDocuments(filter);
    const reports = await AdminReport.find(filter)
      .sort(sortOption)
      .skip(skip)
      .limit(limitNum)
      .lean();

    res.status(200).json({
      success: true,
      reports,
      pagination: {
        page: pageNum,
        limit: limitNum,
        total,
        totalPages: Math.ceil(total / limitNum),
      },
    });
  } catch (error) {
    console.error("❌ Error fetching reports:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch reports",
      error: error.message,
    });
  }
};

/**
 * Get report by ID
 */
export const getReportById = async (req, res) => {
  try {
    const { id } = req.params;
    const report = await AdminReport.findById(id);

    if (!report) {
      return res.status(404).json({
        success: false,
        message: "Report not found",
      });
    }

    // Update view count
    report.viewCount = (report.viewCount || 0) + 1;
    report.lastViewedAt = new Date();
    await report.save();

    // Log activity
    await logActivity(req, "report_viewed", `Viewed report: ${report.reportName}`, {
      reportId: report._id,
      trackingNumber: report.trackingNumber,
    });

    res.status(200).json({
      success: true,
      report,
    });
  } catch (error) {
    console.error("❌ Error fetching report:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch report",
      error: error.message,
    });
  }
};

/**
 * Download report PDF file directly
 */
export const downloadReportPDF = async (req, res) => {
  try {
    const { id } = req.params;
    const report = await AdminReport.findById(id);

    if (!report) {
      return res.status(404).json({
        success: false,
        message: "Report not found",
      });
    }

    // Try to get PDF from temp folder first (if still exists)
    const tempDir = path.join(process.cwd(), "temp");
    const tempPdfPath = path.join(tempDir, report.fileName);

    // Check if temp file exists
    if (fs.existsSync(tempPdfPath)) {
      // Update download count
      report.downloadCount = (report.downloadCount || 0) + 1;
      report.lastDownloadedAt = new Date();
      await report.save();

      // Log activity
      await logActivity(req, "report_downloaded", `Downloaded report: ${report.reportName}`, {
        reportId: report._id,
        trackingNumber: report.trackingNumber,
      });

      // Send PDF file
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="${report.fileName}"`);
      return res.sendFile(path.resolve(tempPdfPath));
    }

    // If temp file doesn't exist, return Drive link (fallback)
    if (report.driveLink) {
      return res.status(200).json({
        success: true,
        downloadLink: report.driveLink,
        fileName: report.fileName,
        trackingNumber: report.trackingNumber,
        message: "File available in Google Drive",
      });
    }

    return res.status(404).json({
      success: false,
      message: "Report file not available",
    });
  } catch (error) {
    console.error("❌ Error downloading report PDF:", error);
    res.status(500).json({
      success: false,
      message: "Failed to download report",
      error: error.message,
    });
  }
};

/**
 * Download report from Google Drive (legacy method)
 */
export const downloadReport = async (req, res) => {
  try {
    const { id } = req.params;
    const report = await AdminReport.findById(id);

    if (!report) {
      return res.status(404).json({
        success: false,
        message: "Report not found",
      });
    }

    if (!report.driveLink || !report.driveFileId) {
      return res.status(400).json({
        success: false,
        message: "Report file not available in Google Drive",
      });
    }

    // Update download count
    report.downloadCount = (report.downloadCount || 0) + 1;
    report.lastDownloadedAt = new Date();
    await report.save();

    // Log activity
    await logActivity(req, "report_downloaded", `Downloaded report: ${report.reportName}`, {
      reportId: report._id,
      trackingNumber: report.trackingNumber,
    });

    // Return download link
    res.status(200).json({
      success: true,
      downloadLink: report.driveLink,
      fileName: report.fileName,
      trackingNumber: report.trackingNumber,
    });
  } catch (error) {
    console.error("❌ Error downloading report:", error);
    res.status(500).json({
      success: false,
      message: "Failed to download report",
      error: error.message,
    });
  }
};

/**
 * Get counselors list for filter dropdown
 */
export const getCounselorsList = async (req, res) => {
  try {
    const counselors = await Counselor.find({ role: "counselor" })
      .select("name email _id")
      .lean();

    res.status(200).json({
      success: true,
      counselors: counselors.map((c) => ({
        id: c._id,
        name: c.name || c.email,
        email: c.email,
      })),
    });
  } catch (error) {
    console.error("❌ Error fetching counselors:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch counselors",
      error: error.message,
    });
  }
};

